apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-webapp
  template:
    metadata:
      labels:
        app: notes-webapp
    spec:
      containers:
        - name: notes-webapp
          image: abdulwadood001/notes-webapp:latest
          ports:
            - containerPort: 3000
          env:
            - name: PGHOST
              value: postgres
            - name: PGUSER
              value: appuser
            - name: PGPASSWORD
              value: apppassword
            - name: PGDATABASE
              value: appdb
            - name: PORT
              value: "3000"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 30