apiVersion: v1
kind: Service
metadata:
  name: notes-webapp-svc
  namespace: default
  labels:
    app: notes-webapp
spec:
  type: NodePort
  selector:
    app: notes-webapp
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080